/** Nombres sugeridos para el campo de icono del formulario de secciones. */
export const SUGGESTED_ICON_NAMES = [
  "Folder",
  "Bookmark",
  "Star",
  "Heart",
  "Home",
  "User",
  "Users",
  "Briefcase",
  "BookOpen",
  "Calendar",
  "Tag",
  "Archive",
  "Film",
  "Music",
  "Gamepad2",
  "Utensils",
  "Plane",
  "Car",
  "ShoppingCart",
  "Wrench",
  "Lock",
  "KeyRound",
  "Globe",
  "Link",
  "File",
  "Image",
  "Code",
  "Database",
  "Cloud",
  "Shield",
] as const;
